"""Compare LLM survey distributions to real EVS human survey data.

Core analysis: do LLMs trained on language X produce value distributions
that resemble country X's actual survey responses?

Report figures (--figure report):
    F2_inglehart_welzel.png   — Inglehart-Welzel composite scatter
    F3_ev_scatter.png         — EV scatter with z-scored row
    F4_jsd_heatmap.png        — Bias-weighted JSD heatmap with mean±std
    F4_jsd_distribution.png   — Per-question JSD histogram with thresholds
    F5_deepdive.png           — Per-question deep dive (3×3 grid)
    F5_umap_grid.png          — 4×2 UMAP grid (metric × filter + uncentered row)
    jsd_vs_bias.png           — JSD vs position bias diagnostic scatter
    umap_sensitivity.png      — UMAP hyperparameter sweep with trustworthiness
  (F6/F7 are generated by analyze.py: P_valid heatmap, position bias)

Usage:
    # Generate all report figures + compile PDF:
    python -m analysis.compare_to_human --db data/survey.db --figure report

    # Generate a single figure:
    python -m analysis.compare_to_human --db data/survey.db --figure umap_grid
"""

import argparse
import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
import seaborn as sns
from scipy.spatial.distance import jensenshannon
from scipy.stats import pearsonr, spearmanr
from sklearn.impute import SimpleImputer

from analysis.constants import (
    LANG_NAMES, CULTURAL_CLUSTERS, LANG_TO_CLUSTER, CLUSTER_COLORS,
    MODEL_COLORS, MODEL_LABELS, MODEL_MARKERS, ORDINAL_TYPES,
    MODELS_EXCLUDE, IW_TRADITIONAL_SECULAR, IW_SURVIVAL_SELFEXPR,
    DEEPDIVE_IW_QUESTIONS, DEEPDIVE_LANGS,
)


# ── Data Loading ─────────────────────────────────────────────────────────────

def load_llm_results(results_dir: Path, db_path: str | None = None) -> pd.DataFrame:
    """Load LLM results, from DB if db_path given, else from parquet files."""
    if db_path:
        from db.load import load_results
        df = load_results(db_path)
        print(f"Loaded {len(df)} LLM rows from {db_path}")
        return df

    frames = []
    for path in sorted(results_dir.glob("*.parquet")):
        if "rephrase" in path.stem or "validate" in path.stem:
            continue
        stem = path.stem
        parts = stem.rsplit("_", 1)
        if len(parts) != 2:
            continue
        model_type, lang = parts
        df = pd.read_parquet(path)
        df["model_type"] = model_type
        df["lang"] = lang
        frames.append(df)
    if not frames:
        print(f"ERROR: No LLM result parquets found in {results_dir}")
        sys.exit(1)
    combined = pd.concat(frames, ignore_index=True)
    print(f"Loaded {len(combined)} LLM rows from {len(frames)} files")
    return combined


def load_question_metadata(questions_path: Path) -> dict:
    """Load questions.json, return dict keyed by canonical_id."""
    with open(questions_path) as f:
        data = json.load(f)
    meta = {}
    for q in data["questions"]:
        qid = q["canonical_id"]
        meta[qid] = {
            "response_type": q["response_type"],
            "option_count": q["option_count"],
        }
    return meta


def build_distributions(df: pd.DataFrame, prob_col: str, group_cols: list[str]) -> dict:
    """Build {(group_key): {response_value: prob}} from a DataFrame.

    Normalizes probabilities to sum to 1 per group.
    """
    distributions = {}
    for group_key, grp in df.groupby(group_cols):
        grp_sorted = grp.sort_values("response_value")
        values = grp_sorted["response_value"].values
        probs = grp_sorted[prob_col].values
        total = probs.sum()
        if total > 0:
            probs = probs / total
        else:
            probs = np.ones(len(probs)) / len(probs)
        distributions[group_key] = dict(zip(values, probs))
    return distributions


def align_distributions(dist_a: dict, dist_b: dict) -> tuple[np.ndarray, np.ndarray]:
    """Align two {value: prob} dicts to arrays over shared values."""
    all_values = sorted(set(dist_a.keys()) | set(dist_b.keys()))
    a = np.array([dist_a.get(v, 0.0) for v in all_values])
    b = np.array([dist_b.get(v, 0.0) for v in all_values])
    # Re-normalize
    if a.sum() > 0:
        a = a / a.sum()
    if b.sum() > 0:
        b = b / b.sum()
    return a, b


# ── Analysis Functions ───────────────────────────────────────────────────────

def compute_jsd_per_question(
    llm_dists: dict,
    human_dists: dict,
    questions: dict,
) -> pd.DataFrame:
    """Compute JSD(LLM, human) for each (model_type, lang, question_id).

    Returns DataFrame with columns:
        model_type, lang, question_id, response_type, jsd, expected_llm, expected_human
    """
    rows = []

    for (mt, lang, qid), llm_dist in llm_dists.items():
        human_key = (lang, qid)
        if human_key not in human_dists:
            continue

        human_dist = human_dists[human_key]
        a, b = align_distributions(llm_dist, human_dist)
        all_values = sorted(set(llm_dist.keys()) | set(human_dist.keys()))

        jsd = jensenshannon(a, b)

        # Expected values for ordinal questions
        rtype = questions.get(qid, {}).get("response_type", "unknown")
        values_arr = np.array(all_values, dtype=float)
        if rtype in ORDINAL_TYPES:
            ev_llm = np.dot(values_arr, a)
            ev_human = np.dot(values_arr, b)
        else:
            ev_llm = np.nan
            ev_human = np.nan

        rows.append({
            "model_type": mt,
            "lang": lang,
            "question_id": qid,
            "response_type": rtype,
            "jsd": jsd,
            "expected_llm": ev_llm,
            "expected_human": ev_human,
        })

    return pd.DataFrame(rows)


def print_summary(jsd_df: pd.DataFrame):
    """Print overall summary statistics."""
    print(f"\n{'='*70}")
    print("LLM vs HUMAN COMPARISON SUMMARY")
    print(f"{'='*70}")
    print(f"Total comparisons: {len(jsd_df)}")
    print(f"Model types: {sorted(jsd_df['model_type'].unique())}")
    print(f"Languages: {jsd_df['lang'].nunique()}")
    print(f"Questions: {jsd_df['question_id'].nunique()}")

    # Overall JSD
    print(f"\n--- Overall JSD ---")
    for mt in sorted(jsd_df["model_type"].unique()):
        sub = jsd_df[jsd_df["model_type"] == mt]
        print(f"  {mt}: mean={sub['jsd'].mean():.4f}, "
              f"median={sub['jsd'].median():.4f}, "
              f"std={sub['jsd'].std():.4f}")

    # Correlation for ordinal questions
    ordinal = jsd_df[jsd_df["response_type"].isin(ORDINAL_TYPES)].dropna(
        subset=["expected_llm", "expected_human"]
    )
    if len(ordinal) > 2:
        print(f"\n--- Expected Value Correlation (ordinal questions, n={len(ordinal)}) ---")
        for mt in sorted(ordinal["model_type"].unique()):
            sub = ordinal[ordinal["model_type"] == mt]
            if len(sub) > 2:
                r_p, p_p = pearsonr(sub["expected_llm"], sub["expected_human"])
                r_s, p_s = spearmanr(sub["expected_llm"], sub["expected_human"])
                print(f"  {mt}: Pearson r={r_p:.3f} (p={p_p:.2e}), "
                      f"Spearman rho={r_s:.3f} (p={p_s:.2e})")

    # JSD by response type
    print(f"\n--- JSD by Response Type ---")
    for rt in sorted(jsd_df["response_type"].unique()):
        sub = jsd_df[jsd_df["response_type"] == rt]
        print(f"  {rt:<14} mean={sub['jsd'].mean():.4f}  "
              f"median={sub['jsd'].median():.4f}  n={len(sub)}")

    # Per-model per-language comparison
    model_types = sorted(jsd_df["model_type"].unique())
    print(f"\n--- Per-Model Mean JSD to Human by Language ---")
    header = f"  {'lang':<5}" + "".join(f"  {MODEL_LABELS.get(mt, mt):>14}" for mt in model_types) + "  closest"
    print(header)
    for lang in sorted(jsd_df["lang"].unique()):
        vals = {}
        parts = f"  {lang:<5}"
        for mt in model_types:
            sub = jsd_df[(jsd_df["model_type"] == mt) & (jsd_df["lang"] == lang)]
            if len(sub) > 0:
                vals[mt] = sub["jsd"].mean()
                parts += f"  {vals[mt]:>14.4f}"
            else:
                parts += f"  {'—':>14}"
        if vals:
            winner = min(vals, key=vals.get)
            parts += f"  {MODEL_LABELS.get(winner, winner)}"
        print(parts)


# ── F1: Human-Fitted UMAP ────────────────────────────────────────────────────

def _build_ev_matrix(dists: dict, group_type: str, questions: dict):
    """Build expected-value matrix from distribution dicts.

    group_type: "human" → keys are (lang, qid), "llm" → keys are (mt, lang, qid)
    Returns (matrix DataFrame indexed by row label, column=question_id).
    """
    rows = []
    for key, dist in dists.items():
        if group_type == "human":
            lang, qid = key
            row_label = lang
        else:
            mt, lang, qid = key
            row_label = f"{mt}_{lang}"

        rtype = questions.get(qid, {}).get("response_type", "unknown")
        if rtype not in ORDINAL_TYPES:
            continue

        all_vals = sorted(dist.keys())
        probs = np.array([dist[v] for v in all_vals])
        total = probs.sum()
        if total > 0:
            probs = probs / total
        vals = np.array(all_vals, dtype=float)
        ev = np.dot(vals, probs)
        rows.append({"row_label": row_label, "question_id": qid, "ev": ev})

    if not rows:
        return pd.DataFrame()
    df = pd.DataFrame(rows)
    pivot = df.pivot_table(index="row_label", columns="question_id",
                           values="ev", aggfunc="first")
    return pivot


# ── F1: Geometry-of-Variation UMAP (centered + correlation) ─────────────────

def _prepare_ev_matrices(llm_dists, human_dists, questions, exclude_qs=None):
    """Shared data prep for UMAP variants: build & align EV matrices, impute."""
    human_pivot = _build_ev_matrix(human_dists, "human", questions)
    llm_pivot = _build_ev_matrix(llm_dists, "llm", questions)

    llm_pivot = llm_pivot[
        ~llm_pivot.index.str.startswith(tuple(f"{m}_" for m in MODELS_EXCLUDE))
    ]

    shared_qs = sorted(set(human_pivot.columns) & set(llm_pivot.columns))
    if exclude_qs:
        shared_qs = [q for q in shared_qs if q not in exclude_qs]
    human_aligned = human_pivot[shared_qs]
    llm_aligned = llm_pivot[shared_qs]

    imputer = SimpleImputer(strategy="mean")
    X_human = pd.DataFrame(
        imputer.fit_transform(human_aligned.values),
        index=human_aligned.index, columns=shared_qs,
    )
    X_llm = pd.DataFrame(
        imputer.transform(llm_aligned.values),
        index=llm_aligned.index, columns=shared_qs,
    )
    return X_human, X_llm, shared_qs


def _get_outlier_questions(jsd_df: pd.DataFrame, threshold: float = 0.35) -> set:
    """Identify questions with bias-weighted mean JSD above the given threshold.

    These are questions where LLMs systematically fail — high mean JSD
    across all (model, language) pairs. Removing them isolates the
    cultural signal from questions where the methodology works.
    Questions with high position bias contribute less to the mean.
    """
    filtered = jsd_df[~jsd_df["model_type"].isin(MODELS_EXCLUDE)]
    if "bias_weight" in filtered.columns:
        def _wmean(grp):
            w = grp["bias_weight"]
            j = grp["jsd"]
            w_sum = w.sum()
            return (j * w).sum() / w_sum if w_sum > 0 else j.mean()
        q_jsd = filtered.groupby("question_id").apply(_wmean, include_groups=False)
    else:
        q_jsd = filtered.groupby("question_id")["jsd"].mean()
    outliers = set(q_jsd[q_jsd > threshold].index)
    print(f"  JSD threshold: {threshold:.2f}, "
          f"excluding {len(outliers)}/{len(q_jsd)} questions")
    return outliers


def _get_quality_filtered_questions(
    jsd_df: pd.DataFrame,
    jsd_threshold: float | None = None,
    bias_threshold: float | None = None,
) -> set:
    """Identify questions failing quality criteria.

    Quality filtering uses prompt-insensitivity (low position bias) and
    distributional distance (JSD) to exclude questions where the LLM
    methodology produced unreliable results.

    Returns set of question_ids to EXCLUDE.
    """
    filtered = jsd_df[~jsd_df["model_type"].isin(MODELS_EXCLUDE)]
    q_stats = filtered.groupby("question_id").agg(
        mean_jsd=("jsd", "mean"),
        mean_bias=("position_bias_magnitude", "mean"),
    ).reset_index()

    excl = set()
    if jsd_threshold is not None:
        excl |= set(q_stats[q_stats["mean_jsd"] > jsd_threshold]["question_id"])
    if bias_threshold is not None:
        excl |= set(q_stats[q_stats["mean_bias"] > bias_threshold]["question_id"])
    return excl


def compute_centered_umap(llm_dists, human_dists, questions, exclude_qs=None):
    """Human-fitted centered UMAP: LLM groups shifted to align with human centroid."""
    from umap import UMAP

    X_human, X_llm, shared_qs = _prepare_ev_matrices(
        llm_dists, human_dists, questions, exclude_qs=exclude_qs
    )

    # Human-fitted centering: human defines the coordinate frame
    human_mean = X_human.mean(axis=0)
    X_human_c = X_human  # no centering — humans are the reference frame

    llm_labels = list(X_llm.index)
    model_types = {}
    for label in llm_labels:
        mt = label.rsplit("_", 1)[0]
        model_types.setdefault(mt, []).append(label)

    # Shift each LLM model family so its centroid aligns with the human centroid
    X_llm_c = X_llm.copy()
    for mt, labels in model_types.items():
        group = X_llm.loc[labels]
        X_llm_c.loc[labels] = (group - group.mean(axis=0) + human_mean).values

    X_all = np.vstack([X_human_c.values, X_llm_c.values])
    reducer = UMAP(n_components=2, n_neighbors=10, min_dist=0.3, random_state=42)
    coords = reducer.fit_transform(X_all)

    n_h = len(X_human_c)
    print(f"  Centered UMAP: {n_h} human, {len(llm_labels)} LLM, "
          f"{len(shared_qs)} questions")
    return coords[:n_h], coords[n_h:], list(X_human_c.index), llm_labels


def compute_centered_correlation_umap(llm_dists, human_dists, questions, exclude_qs=None):
    """Human-fitted centering + correlation distance UMAP.

    First shifts LLM group centroids to align with the human centroid,
    then uses correlation distance which additionally normalizes each
    point's cross-question pattern (removes per-point mean and scale).
    These operate on different axes and are complementary.
    """
    from umap import UMAP

    X_human, X_llm, shared_qs = _prepare_ev_matrices(
        llm_dists, human_dists, questions, exclude_qs=exclude_qs
    )

    # Human-fitted centering: human defines the coordinate frame
    human_mean = X_human.mean(axis=0)
    X_human_c = X_human  # no centering — humans are the reference frame

    llm_labels = list(X_llm.index)
    model_types = {}
    for label in llm_labels:
        mt = label.rsplit("_", 1)[0]
        model_types.setdefault(mt, []).append(label)

    # Shift each LLM model family so its centroid aligns with the human centroid
    X_llm_c = X_llm.copy()
    for mt, labels in model_types.items():
        group = X_llm.loc[labels]
        X_llm_c.loc[labels] = (group - group.mean(axis=0) + human_mean).values

    # Then correlation distance on the centered residuals
    X_all = np.vstack([X_human_c.values, X_llm_c.values])
    reducer = UMAP(
        n_components=2, n_neighbors=10, min_dist=0.3,
        metric="correlation", random_state=42,
    )
    coords = reducer.fit_transform(X_all)

    n_h = len(X_human_c)
    print(f"  Centered+Correlation UMAP: {n_h} human, {len(llm_labels)} LLM, "
          f"{len(shared_qs)} questions")
    return coords[:n_h], coords[n_h:], list(X_human_c.index), llm_labels


def compute_uncentered_umap(llm_dists, human_dists, questions, exclude_qs=None):
    """Uncentered UMAP: raw expected values without any centering, for transparency."""
    from umap import UMAP

    X_human, X_llm, shared_qs = _prepare_ev_matrices(
        llm_dists, human_dists, questions, exclude_qs=exclude_qs
    )

    llm_labels = list(X_llm.index)
    X_all = np.vstack([X_human.values, X_llm.values])
    reducer = UMAP(n_components=2, n_neighbors=10, min_dist=0.3, random_state=42)
    coords = reducer.fit_transform(X_all)

    n_h = len(X_human)
    print(f"  Uncentered UMAP: {n_h} human, {len(llm_labels)} LLM, "
          f"{len(shared_qs)} questions")
    return coords[:n_h], coords[n_h:], list(X_human.index), llm_labels


def _plot_umap_panel(
    ax,
    human_coords: np.ndarray,
    llm_coords: np.ndarray,
    human_labels: list[str],
    llm_labels: list[str],
    title: str,
):
    """Plot a single combined UMAP panel with all models."""
    human_by_lang = {lang: human_coords[i] for i, lang in enumerate(human_labels)}

    # Gray lines LLM→human
    for i, label in enumerate(llm_labels):
        lang = label.rsplit("_", 1)[1]
        if lang in human_by_lang:
            ax.plot(
                [llm_coords[i, 0], human_by_lang[lang][0]],
                [llm_coords[i, 1], human_by_lang[lang][1]],
                color="#cccccc", linewidth=0.6, alpha=0.4, zorder=1,
            )

    # Human points
    for i, lang in enumerate(human_labels):
        cluster = LANG_TO_CLUSTER.get(lang, "Other")
        color = CLUSTER_COLORS.get(cluster, "#999999")
        ax.scatter(human_coords[i, 0], human_coords[i, 1], c=color,
                   s=200, edgecolors="black", linewidths=1.2, zorder=5,
                   marker="o")
        ax.annotate(LANG_NAMES.get(lang, lang),
                    (human_coords[i, 0], human_coords[i, 1]),
                    textcoords="offset points", xytext=(7, 7),
                    fontsize=7, fontweight="bold", alpha=0.9)

    # LLM points — all models on same panel, with language labels
    for i, label in enumerate(llm_labels):
        mt = label.rsplit("_", 1)[0]
        lang = label.rsplit("_", 1)[1]
        cluster = LANG_TO_CLUSTER.get(lang, "Other")
        color = CLUSTER_COLORS.get(cluster, "#999999")
        marker = MODEL_MARKERS.get(mt, "D")
        ax.scatter(llm_coords[i, 0], llm_coords[i, 1], c=color,
                   s=60, marker=marker, edgecolors="black",
                   linewidths=0.5, alpha=0.7, zorder=3)
        ax.annotate(LANG_NAMES.get(lang, lang),
                    (llm_coords[i, 0], llm_coords[i, 1]),
                    textcoords="offset points", xytext=(4, 4),
                    fontsize=4, alpha=0.6, zorder=4)

    ax.set_title(title, fontsize=13, fontweight="bold")
    ax.set_xlabel("UMAP 1")
    ax.set_ylabel("UMAP 2")
    ax.grid(True, alpha=0.2)


def _compute_trustworthiness(X_high, coords, n_neighbors=10):
    """Compute UMAP trustworthiness score."""
    from sklearn.manifold import trustworthiness
    return trustworthiness(X_high, coords, n_neighbors=n_neighbors)


def _save_umap_legend(llm_labels: list[str], figures_dir: Path):
    """Save the shared UMAP legend as a separate image."""
    cluster_handles = [mpatches.Patch(color=c, label=cl)
                       for cl, c in CLUSTER_COLORS.items()]
    source_handles = [
        plt.Line2D([0], [0], marker="o", color="w", markerfacecolor="gray",
                   markersize=11, markeredgecolor="black", label="Human (EVS)"),
    ]
    seen_mt = {}
    for label in llm_labels:
        mt = label.rsplit("_", 1)[0]
        if mt not in seen_mt:
            seen_mt[mt] = MODEL_MARKERS.get(mt, "D")
    for mt, marker in sorted(seen_mt.items()):
        source_handles.append(
            plt.Line2D([0], [0], marker=marker, color="w", markerfacecolor="gray",
                       markersize=7, markeredgecolor="black",
                       label=MODEL_LABELS.get(mt, mt))
        )

    fig_leg, ax_leg = plt.subplots(figsize=(12, 0.8))
    ax_leg.axis("off")
    all_handles = cluster_handles + source_handles
    ax_leg.legend(handles=all_handles, loc="center",
                  ncol=len(all_handles), fontsize=9, framealpha=0.9)
    plt.tight_layout()
    out = figures_dir / "F5_umap_legend.png"
    fig_leg.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig_leg)
    print(f"  Saved {out}")


def plot_umap_grid(
    llm_dists, human_dists, questions, jsd_df, figures_dir: Path,
):
    """F5: Generate individual UMAP panel-pair images for typst layout."""
    from umap import UMAP  # noqa: F811 — ensure import error propagates

    thresholds = [None, 0.35, 0.25]
    _, _, all_qs = _prepare_ev_matrices(llm_dists, human_dists, questions)
    all_qs_set = set(all_qs)

    def _save_panel_pair(euc_data, corr_data, euc_title, corr_title, filename):
        """Save a pair of UMAP panels (Euclidean + Correlation) as one image."""
        fig, axes = plt.subplots(1, 2, figsize=(16, 7))
        _plot_umap_panel(axes[0], *euc_data, title=euc_title)
        _plot_umap_panel(axes[1], *corr_data, title=corr_title)
        plt.tight_layout()
        out = figures_dir / filename
        fig.savefig(out, dpi=150)
        plt.close(fig)
        print(f"  Saved {out}")

    # Row 0: Uncentered (raw expected values, no centering)
    X_human, X_llm, shared_qs = _prepare_ev_matrices(
        llm_dists, human_dists, questions
    )
    X_all_raw = np.vstack([X_human.values, X_llm.values])
    n_kept = len(all_qs)
    row_label = f"No filter ({n_kept} questions)"

    uncent_euc_res = compute_uncentered_umap(
        llm_dists, human_dists, questions, exclude_qs=None
    )
    trust_euc = _compute_trustworthiness(X_all_raw, np.vstack([uncent_euc_res[0], uncent_euc_res[1]]))

    # Uncentered correlation UMAP
    from umap import UMAP as _UMAP
    reducer_corr = _UMAP(n_components=2, n_neighbors=10, min_dist=0.3,
                         metric="correlation", random_state=42)
    coords_corr = reducer_corr.fit_transform(X_all_raw)
    n_h = len(X_human)
    trust_corr = _compute_trustworthiness(X_all_raw, coords_corr)
    uncent_corr_res = (
        coords_corr[:n_h], coords_corr[n_h:],
        list(X_human.index), list(X_llm.index),
    )

    _save_panel_pair(
        uncent_euc_res, uncent_corr_res,
        f"Uncentered Euclidean — {row_label} (T={trust_euc:.3f})",
        f"Uncentered Correlation — {row_label} (T={trust_corr:.3f})",
        "F5_umap_uncentered.png",
    )

    # Rows 1-3: Centered with progressive filtering
    last_llm_labels = None
    for row_idx, thresh in enumerate(thresholds):
        if thresh is None:
            exclude = None
            n_kept = len(all_qs)
            row_label = f"No filter ({n_kept} questions)"
            suffix = "nofilter"
        else:
            exclude = _get_outlier_questions(jsd_df, threshold=thresh)
            n_kept = len(all_qs) - len(exclude & all_qs_set)
            row_label = f"JSD < {thresh} ({n_kept} questions)"
            suffix = f"jsd{str(thresh).replace('.', '')}"

        # Prepare high-dim data for trustworthiness
        X_h, X_l, _ = _prepare_ev_matrices(
            llm_dists, human_dists, questions, exclude_qs=exclude
        )
        h_mean = X_h.mean(axis=0)
        X_h_c = X_h.copy()
        X_l_c = X_l.copy()
        llm_labs = list(X_l.index)
        mt_groups = {}
        for lab in llm_labs:
            m = lab.rsplit("_", 1)[0]
            mt_groups.setdefault(m, []).append(lab)
        for m, labs in mt_groups.items():
            grp = X_l.loc[labs]
            X_l_c.loc[labs] = (grp - grp.mean(axis=0) + h_mean).values
        X_all_centered = np.vstack([X_h_c.values, X_l_c.values])

        # Euclidean
        euc_res = compute_centered_umap(
            llm_dists, human_dists, questions, exclude_qs=exclude
        )
        euc_coords = np.vstack([euc_res[0], euc_res[1]])
        trust_euc = _compute_trustworthiness(X_all_centered, euc_coords)

        # Correlation
        corr_res = compute_centered_correlation_umap(
            llm_dists, human_dists, questions, exclude_qs=exclude
        )
        corr_coords = np.vstack([corr_res[0], corr_res[1]])
        trust_corr = _compute_trustworthiness(X_all_centered, corr_coords)

        _save_panel_pair(
            euc_res, corr_res,
            f"Centered Euclidean — {row_label} (T={trust_euc:.3f})",
            f"Centered Correlation — {row_label} (T={trust_corr:.3f})",
            f"F5_umap_{suffix}.png",
        )
        last_llm_labels = euc_res[3]

    # Save shared legend
    if last_llm_labels:
        _save_umap_legend(last_llm_labels, figures_dir)


def plot_jsd_distribution(jsd_df: pd.DataFrame, figures_dir: Path):
    """F4: Per-question JSD histogram with threshold lines."""
    filtered = jsd_df[~jsd_df["model_type"].isin(MODELS_EXCLUDE)]
    q_jsd = filtered.groupby("question_id")["jsd"].mean().sort_values()

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.hist(q_jsd.values, bins=40, color="#4a90d9", edgecolor="black",
            linewidth=0.5, alpha=0.85)

    # Threshold lines
    for thresh, color, style in [
        (0.35, "#cc3333", "--"),
        (0.25, "#33aa33", "-."),
    ]:
        n_below = (q_jsd < thresh).sum()
        ax.axvline(thresh, color=color, linestyle=style, linewidth=2,
                   label=f"JSD = {thresh} ({n_below}/{len(q_jsd)} questions retained)")

    ax.set_xlabel("Mean JSD (across all models and languages)", fontsize=12)
    ax.set_ylabel("Number of Questions", fontsize=12)
    ax.set_title("F4: Per-Question JSD Distribution with Filtering Thresholds",
                 fontsize=13, fontweight="bold")
    ax.legend(fontsize=10, framealpha=0.9)
    ax.grid(True, alpha=0.3, axis="y")

    plt.tight_layout()
    out = figures_dir / "F4_jsd_distribution.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  Saved {out}")


# ── F2: Inglehart-Welzel Composite ──────────────────────────────────────────

def compute_iw_composites(
    llm_dists: dict,
    human_dists: dict,
    questions: dict,
) -> pd.DataFrame:
    """Compute Inglehart-Welzel composite scores for human and LLM sources.

    Returns DataFrame: source, lang, trad_secular, surv_selfexpr
    """
    all_iw_qs = {**IW_TRADITIONAL_SECULAR, **IW_SURVIVAL_SELFEXPR}

    # Collect expected values per (source, lang, qid)
    ev_rows = []

    # Human EVs
    for (lang, qid), dist in human_dists.items():
        if qid not in all_iw_qs:
            continue
        vals = sorted(dist.keys())
        probs = np.array([dist[v] for v in vals])
        total = probs.sum()
        if total > 0:
            probs = probs / total
        ev = np.dot(np.array(vals, dtype=float), probs)
        ev_rows.append({"source": "human", "lang": lang, "qid": qid, "ev": ev})

    # LLM EVs
    for (mt, lang, qid), dist in llm_dists.items():
        if qid not in all_iw_qs or mt in MODELS_EXCLUDE:
            continue
        vals = sorted(dist.keys())
        probs = np.array([dist[v] for v in vals])
        total = probs.sum()
        if total > 0:
            probs = probs / total
        ev = np.dot(np.array(vals, dtype=float), probs)
        ev_rows.append({"source": mt, "lang": lang, "qid": qid, "ev": ev})

    ev_df = pd.DataFrame(ev_rows)
    if ev_df.empty:
        return pd.DataFrame()

    # Apply polarity flips
    def flip_ev(row):
        info = all_iw_qs.get(row["qid"], {})
        if info.get("flip", False):
            max_val = info.get("max_val")
            if max_val is not None:
                return max_val - row["ev"]
            # Fallback: use data max for this question
            q_max = ev_df[ev_df["qid"] == row["qid"]]["ev"].max()
            return q_max - row["ev"]
        return row["ev"]

    ev_df["ev_flipped"] = ev_df.apply(flip_ev, axis=1)

    # Per-question quantile normalization across all (source, lang) jointly
    for qid in ev_df["qid"].unique():
        mask = ev_df["qid"] == qid
        vals = ev_df.loc[mask, "ev_flipped"]
        if len(vals) > 1:
            ranks = vals.rank(method="average")
            ev_df.loc[mask, "ev_z"] = (ranks - 1) / (len(ranks) - 1)
        else:
            ev_df.loc[mask, "ev_z"] = 0.5

    # Average z-scores within each dimension
    result_rows = []
    for (source, lang), grp in ev_df.groupby(["source", "lang"]):
        # Traditional-Secular
        ts_qs = grp[grp["qid"].isin(IW_TRADITIONAL_SECULAR)]
        if len(ts_qs) >= 3:
            trad_secular = ts_qs["ev_z"].mean()
        else:
            trad_secular = np.nan

        # Survival-SelfExpression
        se_qs = grp[grp["qid"].isin(IW_SURVIVAL_SELFEXPR)]
        if len(se_qs) >= 3:
            surv_selfexpr = se_qs["ev_z"].mean()
        else:
            surv_selfexpr = np.nan

        result_rows.append({
            "source": source,
            "lang": lang,
            "trad_secular": trad_secular,
            "surv_selfexpr": surv_selfexpr,
        })

    return pd.DataFrame(result_rows).dropna()


def plot_iw_composite(iw_df: pd.DataFrame, figures_dir: Path):
    """F2: Inglehart-Welzel composite scatter plot."""
    fig, ax = plt.subplots(figsize=(10, 8))

    # Build human coords lookup
    human = iw_df[iw_df["source"] == "human"]
    human_by_lang = {
        row["lang"]: (row["surv_selfexpr"], row["trad_secular"])
        for _, row in human.iterrows()
    }

    llm = iw_df[iw_df["source"] != "human"]

    # Gray lines LLM→human
    for _, row in llm.iterrows():
        lang = row["lang"]
        if lang in human_by_lang:
            hx, hy = human_by_lang[lang]
            ax.plot([row["surv_selfexpr"], hx], [row["trad_secular"], hy],
                    color="#cccccc", linewidth=0.8, alpha=0.5, zorder=1)

    # LLM points
    for _, row in llm.iterrows():
        cluster = LANG_TO_CLUSTER.get(row["lang"], "Other")
        color = CLUSTER_COLORS.get(cluster, "#999999")
        marker = MODEL_MARKERS.get(row["source"], "D")
        ax.scatter(row["surv_selfexpr"], row["trad_secular"],
                   c=color, marker=marker, s=80, edgecolors="black",
                   linewidths=0.5, alpha=0.8, zorder=3)

    # Human points (large circles with labels)
    for _, row in human.iterrows():
        cluster = LANG_TO_CLUSTER.get(row["lang"], "Other")
        color = CLUSTER_COLORS.get(cluster, "#999999")
        ax.scatter(row["surv_selfexpr"], row["trad_secular"],
                   c=color, s=200, edgecolors="black", linewidths=1.2,
                   zorder=5, marker="o")
        ax.annotate(LANG_NAMES.get(row["lang"], row["lang"]),
                    (row["surv_selfexpr"], row["trad_secular"]),
                    textcoords="offset points", xytext=(7, 7),
                    fontsize=8, fontweight="bold", alpha=0.9)

    # Legends
    cluster_handles = [mpatches.Patch(color=c, label=cl)
                       for cl, c in CLUSTER_COLORS.items()]
    present_models = sorted(llm["source"].unique())
    model_handles = [
        plt.Line2D([0], [0], marker=MODEL_MARKERS.get(mt, "D"), color="w",
                   markerfacecolor="gray", markersize=7,
                   markeredgecolor="black",
                   label=MODEL_LABELS.get(mt, mt))
        for mt in present_models
    ]
    model_handles.append(
        plt.Line2D([0], [0], marker="o", color="w", markerfacecolor="gray",
                   markersize=11, markeredgecolor="black", label="Human (EVS)")
    )
    leg1 = ax.legend(handles=cluster_handles, title="Cultural Cluster",
                     loc="upper left", framealpha=0.9)
    ax.add_artist(leg1)
    ax.legend(handles=model_handles, title="Source",
              loc="lower left", framealpha=0.9)

    ax.set_xlabel("Survival → Self-Expression", fontsize=12)
    ax.set_ylabel("Traditional → Secular-Rational", fontsize=12)
    ax.set_title("F2: Inglehart-Welzel Cultural Map (Composite Scores)",
                 fontsize=14, fontweight="bold")
    ax.grid(True, alpha=0.3)
    ax.axhline(0, color="gray", linewidth=0.5, linestyle="--", alpha=0.5)
    ax.axvline(0, color="gray", linewidth=0.5, linestyle="--", alpha=0.5)

    plt.tight_layout()
    out = figures_dir / "F2_inglehart_welzel.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  Saved {out}")


# ── F3: EV Scatter + Z-Score ────────────────────────────────────────────────

def plot_scatter_ev(jsd_df: pd.DataFrame, figures_dir: Path):
    """F3: 2-row scatter — raw EV (top) and z-scored EV (bottom)."""
    ordinal = jsd_df[
        jsd_df["response_type"].isin(ORDINAL_TYPES)
        & ~jsd_df["model_type"].isin(MODELS_EXCLUDE)
    ].dropna(subset=["expected_llm", "expected_human"])
    if ordinal.empty:
        print("  No ordinal data for scatter plot")
        return

    model_types = sorted(ordinal["model_type"].unique())
    n_models = len(model_types)
    fig, axes = plt.subplots(2, n_models, figsize=(7 * n_models, 11), squeeze=False)

    # Compute z-scores per question (jointly across all sources)
    ordinal = ordinal.copy()
    for qid in ordinal["question_id"].unique():
        mask = ordinal["question_id"] == qid
        # Pool human and LLM values for z-scoring
        all_vals = pd.concat([
            ordinal.loc[mask, "expected_human"],
            ordinal.loc[mask, "expected_llm"],
        ])
        mu, sigma = all_vals.mean(), all_vals.std()
        if sigma > 0:
            ordinal.loc[mask, "z_human"] = (ordinal.loc[mask, "expected_human"] - mu) / sigma
            ordinal.loc[mask, "z_llm"] = (ordinal.loc[mask, "expected_llm"] - mu) / sigma
        else:
            ordinal.loc[mask, "z_human"] = 0.0
            ordinal.loc[mask, "z_llm"] = 0.0

    for row_idx, (x_col, y_col, row_title) in enumerate([
        ("expected_human", "expected_llm", "Raw Expected Value"),
        ("z_human", "z_llm", "Z-Scored Expected Value"),
    ]):
        for idx, mt in enumerate(model_types):
            ax = axes[row_idx, idx]
            sub = ordinal[ordinal["model_type"] == mt]

            for lang in sorted(sub["lang"].unique()):
                lsub = sub[sub["lang"] == lang]
                cluster = LANG_TO_CLUSTER.get(lang, "Other")
                color = CLUSTER_COLORS.get(cluster, "#999999")
                # Scale alpha by bias weight: low-bias questions are more prominent
                alphas = (lsub["bias_weight"].values * 0.5 + 0.05).clip(0.05, 0.55)
                ax.scatter(lsub[x_col], lsub[y_col],
                           c=color, alpha=alphas.mean(), s=15, edgecolors="none")

            r_p, _ = pearsonr(sub[x_col], sub[y_col])
            r_s, _ = spearmanr(sub[x_col], sub[y_col])

            # Regression line
            z = np.polyfit(sub[x_col], sub[y_col], 1)
            x_line = np.linspace(sub[x_col].min(), sub[x_col].max(), 100)
            ax.plot(x_line, np.polyval(z, x_line), "k--", alpha=0.5, linewidth=1)

            # Identity line
            lims = [
                min(ax.get_xlim()[0], ax.get_ylim()[0]),
                max(ax.get_xlim()[1], ax.get_ylim()[1]),
            ]
            ax.plot(lims, lims, "k:", alpha=0.3, linewidth=0.5)
            ax.set_xlim(lims)
            ax.set_ylim(lims)

            mt_label = MODEL_LABELS.get(mt, mt)
            ax.set_title(f"{mt_label}\nr={r_p:.3f}, ρ={r_s:.3f} (n={len(sub)})")
            ax.set_xlabel(f"Human {row_title}")
            ax.set_ylabel(f"LLM {row_title}")
            ax.grid(True, alpha=0.3)

    # Cluster legend
    handles = [mpatches.Patch(color=c, label=cl)
               for cl, c in CLUSTER_COLORS.items()]
    axes[0, -1].legend(handles=handles, title="Cultural Cluster",
                       loc="upper left", fontsize=7, framealpha=0.9)

    plt.suptitle("F3: LLM vs Human Expected Values — Raw (top) and Z-Scored (bottom)",
                 fontsize=14, fontweight="bold")
    plt.tight_layout(rect=[0, 0, 1, 0.96])
    out = figures_dir / "F3_ev_scatter.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  Saved {out}")


# ── F4: JSD Heatmap (revised) ────────────────────────────────────────────────

def plot_jsd_heatmap(jsd_df: pd.DataFrame, figures_dir: Path):
    """F4: Heatmap of bias-weighted mean JSD(LLM, human) by model_type × language."""
    filtered = jsd_df[~jsd_df["model_type"].isin(MODELS_EXCLUDE)]

    # Compute bias-weighted mean JSD per (model, lang) group
    def weighted_mean_jsd(grp):
        w = grp["bias_weight"]
        j = grp["jsd"]
        w_sum = w.sum()
        if w_sum > 0:
            return (j * w).sum() / w_sum
        return j.mean()

    stats_w = filtered.groupby(["model_type", "lang"]).apply(
        weighted_mean_jsd, include_groups=False
    ).reset_index(name="wmean_jsd")

    stats = filtered.groupby(["model_type", "lang"]).agg(
        mean_jsd=("jsd", "mean"),
        std_jsd=("jsd", "std"),
    ).reset_index()
    stats = stats.merge(stats_w, on=["model_type", "lang"], how="left")

    pivot_wmean = stats.pivot_table(
        index="model_type", columns="lang", values="wmean_jsd"
    )
    pivot_std = stats.pivot_table(
        index="model_type", columns="lang", values="std_jsd"
    )

    # Sort columns alphabetically, rename
    cols = sorted(pivot_wmean.columns)
    pivot_wmean = pivot_wmean[cols]
    pivot_std = pivot_std[cols]
    pivot_wmean.columns = [LANG_NAMES.get(c, c) for c in pivot_wmean.columns]
    pivot_std.columns = [LANG_NAMES.get(c, c) for c in pivot_std.columns]
    pivot_wmean.index = [MODEL_LABELS.get(i, i) for i in pivot_wmean.index]
    pivot_std.index = [MODEL_LABELS.get(i, i) for i in pivot_std.index]

    # Build annotation strings: weighted mean ± std
    annot = pivot_wmean.copy().astype(str)
    for r in annot.index:
        for c in annot.columns:
            m = pivot_wmean.loc[r, c]
            s = pivot_std.loc[r, c]
            if pd.notna(m):
                annot.loc[r, c] = f"{m:.3f}\n±{s:.3f}"
            else:
                annot.loc[r, c] = ""

    fig, ax = plt.subplots(figsize=(18, max(4, len(pivot_wmean) * 1.2)))
    sns.heatmap(
        pivot_wmean, annot=annot, fmt="", cmap="RdYlGn_r",
        ax=ax, linewidths=0.5,
        cbar_kws={"label": "Bias-Weighted Mean JSD to Human"},
        annot_kws={"size": 8},
    )
    ax.set_title("F4: Bias-Weighted Mean JSD (LLM vs Human) by Model and Language",
                 fontsize=14, fontweight="bold")
    ax.set_xlabel("Language")
    ax.set_ylabel("Model")
    ax.tick_params(axis="x", rotation=45)
    plt.tight_layout()
    out = figures_dir / "F4_jsd_heatmap.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  Saved {out}")


# ── F5: Per-Question Deep Dive ───────────────────────────────────────────────

def plot_deepdive(
    jsd_df: pd.DataFrame,
    llm_dists: dict,
    human_dists: dict,
    figures_dir: Path,
):
    """F5: 3×3 grid — 3 IW questions + 3 best JSD + 3 worst JSD."""
    filtered = jsd_df[~jsd_df["model_type"].isin(MODELS_EXCLUDE)]

    # Average JSD across all (model_type, lang) for each question
    q_jsd = filtered.groupby("question_id").agg(mean_jsd=("jsd", "mean")).reset_index()
    q_jsd = q_jsd.sort_values("mean_jsd")

    iw_qids = [qid for qid, _ in DEEPDIVE_IW_QUESTIONS]
    best_candidates = [qid for qid in q_jsd.head(10)["question_id"] if qid not in iw_qids]
    worst_candidates = [qid for qid in q_jsd.tail(10)["question_id"].iloc[::-1] if qid not in iw_qids]

    best_3 = best_candidates[:3]
    worst_3 = worst_candidates[:3]
    all_questions = iw_qids + best_3 + worst_3

    # Find best-performing model per question (lowest mean JSD excluding MODELS_EXCLUDE)
    best_model_per_q = {}
    for qid in all_questions:
        q_sub = filtered[filtered["question_id"] == qid]
        if q_sub.empty:
            continue
        mt_jsd = q_sub.groupby("model_type")["jsd"].mean()
        best_model_per_q[qid] = mt_jsd.idxmin()

    # IW question labels
    iw_labels = {qid: text for qid, text in DEEPDIVE_IW_QUESTIONS}

    fig, axes = plt.subplots(3, 3, figsize=(20, 16))
    axes = axes.flatten()

    category_colors = {}
    for qid in iw_qids:
        category_colors[qid] = "#3366cc"  # blue for IW
    for qid in best_3:
        category_colors[qid] = "#33aa33"  # green for best
    for qid in worst_3:
        category_colors[qid] = "#cc3333"  # red for worst

    for idx, qid in enumerate(all_questions):
        ax = axes[idx]
        best_mt = best_model_per_q.get(qid, "hplt2c")
        mean_jsd_val = q_jsd[q_jsd["question_id"] == qid]["mean_jsd"]
        mean_jsd_val = mean_jsd_val.iloc[0] if len(mean_jsd_val) > 0 else np.nan

        n_langs_plotted = 0
        for lang_idx, lang in enumerate(DEEPDIVE_LANGS):
            human_key = (lang, qid)
            llm_key = (best_mt, lang, qid)

            if human_key not in human_dists:
                continue
            human_d = human_dists[human_key]
            all_vals = sorted(human_d.keys())

            human_arr = np.array([human_d.get(v, 0) for v in all_vals])
            if human_arr.sum() > 0:
                human_arr = human_arr / human_arr.sum()

            x = np.arange(len(all_vals))
            width = 0.8 / (2 * len(DEEPDIVE_LANGS))
            offset = (lang_idx - (len(DEEPDIVE_LANGS) - 1) / 2) * width * 2

            lang_name = LANG_NAMES.get(lang, lang)

            # Human bars: thick outlined bars
            ax.bar(x + offset - width / 2, human_arr, width,
                   facecolor="none", edgecolor=CLUSTER_COLORS.get(
                       LANG_TO_CLUSTER.get(lang, "Other"), "#999999"),
                   linewidth=2.0, label=f"Human {lang_name}" if idx == 0 else None)

            # LLM bars: filled thinner bars
            if llm_key in llm_dists:
                llm_d = llm_dists[llm_key]
                llm_arr = np.array([llm_d.get(v, 0) for v in all_vals])
                if llm_arr.sum() > 0:
                    llm_arr = llm_arr / llm_arr.sum()
                ax.bar(x + offset + width / 2, llm_arr, width,
                       color=CLUSTER_COLORS.get(
                           LANG_TO_CLUSTER.get(lang, "Other"), "#999999"),
                       alpha=0.6,
                       label=f"LLM {lang_name}" if idx == 0 else None)

            n_langs_plotted += 1

        ax.set_xticks(np.arange(len(all_vals)))
        ax.set_xticklabels(all_vals, fontsize=7)
        ax.set_ylabel("Probability", fontsize=8)
        ax.grid(True, alpha=0.2, axis="y")

        # Title with color coding
        if qid in iw_labels:
            subtitle = iw_labels[qid]
            category = "IW"
        elif qid in best_3:
            subtitle = f"Best aligned (JSD={mean_jsd_val:.3f})"
            category = "BEST"
        else:
            subtitle = f"Worst aligned (JSD={mean_jsd_val:.3f})"
            category = "WORST"

        title_color = category_colors.get(qid, "black")
        ax.set_title(f"{qid}: {subtitle}\n[{category}] model={MODEL_LABELS.get(best_mt, best_mt)}",
                     fontsize=9, color=title_color, fontweight="bold")

    # Add shared legend
    if len(all_questions) > 0:
        legend_elements = []
        for lang in DEEPDIVE_LANGS:
            color = CLUSTER_COLORS.get(LANG_TO_CLUSTER.get(lang, "Other"), "#999999")
            lang_name = LANG_NAMES.get(lang, lang)
            legend_elements.append(
                mpatches.Patch(facecolor="none", edgecolor=color,
                               linewidth=2, label=f"Human {lang_name}"))
            legend_elements.append(
                mpatches.Patch(facecolor=color, alpha=0.6,
                               label=f"LLM {lang_name}"))
        fig.legend(handles=legend_elements, loc="lower center",
                   ncol=len(DEEPDIVE_LANGS) * 2, fontsize=7, framealpha=0.9)

    plt.suptitle("F5: Per-Question Deep Dive — IW (blue), Best (green), Worst (red)",
                 fontsize=14, fontweight="bold")
    plt.tight_layout(rect=[0, 0.05, 1, 0.95])
    out = figures_dir / "F5_deepdive.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  Saved {out}")


# ── Supplementary: JSD vs Position Bias diagnostic ────────────────────────────

def plot_jsd_vs_bias(jsd_df: pd.DataFrame, figures_dir: Path):
    """Supplementary: scatter of per-question JSD vs position bias magnitude."""
    filtered = jsd_df[~jsd_df["model_type"].isin(MODELS_EXCLUDE)]
    if "position_bias_magnitude" not in filtered.columns:
        print("  Skipping JSD vs bias: no position_bias_magnitude column")
        return

    # Average per question across all (model, lang) pairs
    q_stats = filtered.groupby(["question_id", "response_type"]).agg(
        mean_jsd=("jsd", "mean"),
        mean_bias=("position_bias_magnitude", "mean"),
    ).reset_index()

    fig, ax = plt.subplots(figsize=(8, 6))
    rtype_colors = {
        "likert3": "#1f77b4", "likert4": "#ff7f0e", "likert5": "#2ca02c",
        "likert10": "#d62728", "frequency": "#9467bd",
        "binary": "#8c564b", "categorical": "#e377c2",
    }
    for rtype in sorted(q_stats["response_type"].unique()):
        sub = q_stats[q_stats["response_type"] == rtype]
        color = rtype_colors.get(rtype, "#999999")
        ax.scatter(sub["mean_bias"], sub["mean_jsd"],
                   c=color, s=30, alpha=0.6, label=rtype, edgecolors="none")

    # Correlation annotation
    valid = q_stats.dropna(subset=["mean_jsd", "mean_bias"])
    if len(valid) > 2:
        r_p, p_p = pearsonr(valid["mean_bias"], valid["mean_jsd"])
        ax.annotate(f"r={r_p:.3f}, p={p_p:.2e}", xy=(0.02, 0.98),
                    xycoords="axes fraction", va="top", fontsize=10,
                    bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.8))

    ax.set_xlabel("Mean Position Bias Magnitude", fontsize=12)
    ax.set_ylabel("Mean JSD (LLM vs Human)", fontsize=12)
    ax.set_title("JSD vs Position Bias per Question", fontsize=13, fontweight="bold")
    ax.legend(title="Response Type", fontsize=8, title_fontsize=9)
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    out = figures_dir / "jsd_vs_bias.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  Saved {out}")


# ── Supplementary: UMAP hyperparameter sensitivity ───────────────────────────

def plot_umap_sensitivity(
    llm_dists, human_dists, questions, jsd_df, figures_dir: Path,
):
    """Supplementary: 4×3 UMAP grid sweeping n_neighbors × min_dist with trustworthiness."""
    from umap import UMAP
    from sklearn.manifold import trustworthiness

    # Use centered Euclidean with JSD<0.35 filter (the middle-left config)
    exclude = _get_outlier_questions(jsd_df, threshold=0.35)
    X_human, X_llm, shared_qs = _prepare_ev_matrices(
        llm_dists, human_dists, questions, exclude_qs=exclude
    )

    # Human-fitted centering
    human_mean = X_human.mean(axis=0)
    X_human_c = X_human.copy()  # humans stay at natural coords
    llm_labels = list(X_llm.index)
    model_types_map = {}
    for label in llm_labels:
        mt = label.rsplit("_", 1)[0]
        model_types_map.setdefault(mt, []).append(label)

    X_llm_c = X_llm.copy()
    for mt, labels in model_types_map.items():
        group = X_llm.loc[labels]
        X_llm_c.loc[labels] = (group - group.mean(axis=0) + human_mean).values

    X_all = np.vstack([X_human_c.values, X_llm_c.values])
    human_labels = list(X_human_c.index)
    n_h = len(human_labels)

    n_neighbors_list = [5, 10, 15, 20]
    min_dist_list = [0.1, 0.3, 0.5]

    fig, axes = plt.subplots(
        len(n_neighbors_list), len(min_dist_list),
        figsize=(5 * len(min_dist_list), 5 * len(n_neighbors_list)),
    )

    for i, nn in enumerate(n_neighbors_list):
        for j, md in enumerate(min_dist_list):
            ax = axes[i, j]
            reducer = UMAP(n_components=2, n_neighbors=nn, min_dist=md, random_state=42)
            coords = reducer.fit_transform(X_all)
            trust = trustworthiness(X_all, coords, n_neighbors=10)

            _plot_umap_panel(
                ax,
                coords[:n_h], coords[n_h:],
                human_labels, llm_labels,
                title=f"nn={nn}, md={md} (T={trust:.3f})",
            )

    plt.suptitle(
        "UMAP Sensitivity: n_neighbors × min_dist (Centered Euclidean, JSD<0.35)",
        fontsize=14, fontweight="bold",
    )
    plt.tight_layout(rect=[0, 0, 1, 0.97])
    out = figures_dir / "umap_sensitivity.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  Saved {out}")


# ── PCA-based cultural geography ──────────────────────────────────────────────

def _apply_human_fitted_centering(X_human, X_llm):
    """Apply human-fitted centering: shift LLM families to human centroid.

    Returns centered copies. Human stays at natural coords.
    """
    human_mean = X_human.mean(axis=0)
    X_human_c = X_human.copy()
    X_llm_c = X_llm.copy()

    llm_labels = list(X_llm.index)
    mt_groups = {}
    for label in llm_labels:
        mt = label.rsplit("_", 1)[0]
        mt_groups.setdefault(mt, []).append(label)

    for mt, labels in mt_groups.items():
        group = X_llm.loc[labels]
        X_llm_c.loc[labels] = (group - group.mean(axis=0) + human_mean).values

    return X_human_c, X_llm_c


def _variance_match_pca(human_pca, llm_pca, n_components=None):
    """Variance-match LLM PCA projections to human statistics per axis.

    For each PC axis j, transforms LLM values so their mean and std
    match the human mean and std:
        x'[j] = (x[j] - mean_llm[j]) * (std_human[j] / std_llm[j]) + mean_human[j]

    This removes both the shift (centering) and the scale compression
    (attenuation), leaving only the relative structure for comparison.
    """
    k = n_components or human_pca.shape[1]
    h = human_pca[:, :k].copy()
    l = llm_pca[:, :k].copy()

    h_mean = h.mean(axis=0)
    h_std = h.std(axis=0)

    # Per model family: group by model type prefix
    # But we only have the raw arrays here, not labels — so do it globally
    # (caller can pass per-family slices if needed)
    l_mean = l.mean(axis=0)
    l_std = l.std(axis=0)

    # Avoid division by zero on axes with no LLM variance
    l_std = np.where(l_std > 1e-10, l_std, 1.0)

    l_matched = (l - l_mean) * (h_std / l_std) + h_mean
    return h, l_matched


def _variance_match_pca_per_family(human_pca, llm_pca, llm_labels, n_components=None):
    """Variance-match per model family in PCA space.

    Each model family is independently rescaled to match human statistics.
    """
    k = n_components or human_pca.shape[1]
    h = human_pca[:, :k].copy()
    l = llm_pca[:, :k].copy()

    h_mean = h.mean(axis=0)
    h_std = h.std(axis=0)

    mt_groups = {}
    for i, label in enumerate(llm_labels):
        mt = label.rsplit("_", 1)[0]
        mt_groups.setdefault(mt, []).append(i)

    l_matched = l.copy()
    for mt, indices in mt_groups.items():
        family = l[indices]
        f_mean = family.mean(axis=0)
        f_std = family.std(axis=0)
        f_std = np.where(f_std > 1e-10, f_std, 1.0)
        l_matched[indices] = (family - f_mean) * (h_std / f_std) + h_mean

    return h, l_matched


def plot_pca_comparison(
    llm_dists, human_dists, questions, jsd_df, figures_dir: Path,
):
    """PCA-based cultural geography: UMAP on variance-matched PCA-5.

    PCA is fitted on human expected-value data, LLM data projected into
    human PCA space, then per-model-family variance-matched before UMAP.

    Generates individual panels at progressive quality cutoffs (combining
    JSD threshold and position-bias threshold), plus a scree plot.
    """
    from sklearn.decomposition import PCA
    from umap import UMAP

    _, _, all_qs = _prepare_ev_matrices(llm_dists, human_dists, questions)
    all_qs_set = set(all_qs)

    # Quality cutoffs: (jsd_thresh, bias_thresh, suffix, short_label)
    # Each level gets progressively stricter.
    quality_levels = [
        (None,  None,  "nofilter", "No filter"),
        (0.40,  0.55,  "q1",       "Mild (JSD<0.40, Bias<0.55)"),
        (0.35,  0.50,  "q2",       "Moderate (JSD<0.35, Bias<0.50)"),
        (0.30,  0.45,  "q3",       "Strict (JSD<0.30, Bias<0.45)"),
    ]

    for jsd_t, bias_t, suffix, short_label in quality_levels:
        exclude = _get_quality_filtered_questions(
            jsd_df, jsd_threshold=jsd_t, bias_threshold=bias_t,
        ) if jsd_t is not None else None
        n_excl = len(exclude & all_qs_set) if exclude else 0
        n_kept = len(all_qs_set) - n_excl
        filter_label = f"{short_label} ({n_kept} questions)"
        print(f"  Quality cutoff '{suffix}': {filter_label}")

        X_human, X_llm, shared_qs = _prepare_ev_matrices(
            llm_dists, human_dists, questions, exclude_qs=exclude
        )
        X_human_c, X_llm_c = _apply_human_fitted_centering(X_human, X_llm)
        human_labels = list(X_human_c.index)
        llm_labels = list(X_llm_c.index)

        n_max = min(X_human_c.shape)
        pca = PCA(n_components=n_max, random_state=42)
        human_pca_all = pca.fit_transform(X_human_c.values)
        llm_pca_all = pca.transform(X_llm_c.values)
        var_explained = pca.explained_variance_ratio_
        cumvar = np.cumsum(var_explained)

        k = min(5, n_max)
        h_vmk, l_vmk = _variance_match_pca_per_family(
            human_pca_all, llm_pca_all, llm_labels, n_components=k
        )
        X_vm_all = np.vstack([h_vmk, l_vmk])

        reducer = UMAP(n_components=2, n_neighbors=10, min_dist=0.3, random_state=42)
        coords = reducer.fit_transform(X_vm_all)
        n_h = len(human_labels)
        trust = _compute_trustworthiness(X_vm_all, coords)

        fig, ax = plt.subplots(figsize=(9, 8))
        _plot_umap_panel(
            ax, coords[:n_h], coords[n_h:], human_labels, llm_labels,
            title=(f"UMAP on var-matched PCA-{k} — {filter_label}\n"
                   f"Cumulative variance: {cumvar[k-1]:.1%}, "
                   f"Trustworthiness: {trust:.3f}"),
        )
        plt.tight_layout()
        out = figures_dir / f"F5_pca_{suffix}.png"
        fig.savefig(out, dpi=150)
        plt.close(fig)
        print(f"  Saved {out}")

    # --- Scree plot: variance explained (using moderate quality cutoff) ---
    exclude = _get_quality_filtered_questions(jsd_df, jsd_threshold=0.35, bias_threshold=0.50)
    X_human, X_llm, _ = _prepare_ev_matrices(
        llm_dists, human_dists, questions, exclude_qs=exclude
    )
    X_human_c, _ = _apply_human_fitted_centering(X_human, X_llm)
    n_max = min(X_human_c.shape)
    pca = PCA(n_components=n_max, random_state=42)
    pca.fit(X_human_c.values)
    var_explained = pca.explained_variance_ratio_
    cumvar = np.cumsum(var_explained)

    fig, ax = plt.subplots(figsize=(8, 4))
    n_show = min(20, len(var_explained))
    ax.bar(range(1, n_show + 1), var_explained[:n_show], color="#4a90d9",
           edgecolor="black", linewidth=0.5, alpha=0.85, label="Individual")
    ax.plot(range(1, n_show + 1), cumvar[:n_show], "ro-", markersize=5,
            label="Cumulative")
    ax.set_xlabel("Principal Component")
    ax.set_ylabel("Variance Explained")
    ax.set_title("PCA Scree Plot (fitted on human EVS data, moderate quality filter)")
    ax.legend()
    ax.grid(True, alpha=0.3, axis="y")
    ax.set_xticks(range(1, n_show + 1))
    plt.tight_layout()
    out = figures_dir / "F5_pca_scree.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  Saved {out}")

    # Save legend
    _save_umap_legend(llm_labels, figures_dir)


# ── Procrustes + RSA alignment ────────────────────────────────────────────────

def _procrustes_align(human_pts, llm_pts):
    """Procrustes alignment of LLM points to human points.

    Both inputs: (n_langs, k) arrays with rows in the same language order.
    Returns (human_standardized, llm_aligned, disparity).
    Disparity is sum of squared differences after optimal alignment (lower=better).
    """
    from scipy.spatial import procrustes
    h_aligned, l_aligned, disparity = procrustes(human_pts, llm_pts)
    return h_aligned, l_aligned, disparity


def _rsa_mantel(human_pts, llm_pts, n_perms=10000):
    """Representational Similarity Analysis via Mantel test.

    Computes pairwise distance matrices for human and LLM points,
    then correlates the upper triangles (Mantel test with permutations).
    Returns (r, p_value).
    """
    from scipy.spatial.distance import pdist, squareform
    from scipy.stats import pearsonr

    d_human = pdist(human_pts, metric="euclidean")
    d_llm = pdist(llm_pts, metric="euclidean")

    r_obs, _ = pearsonr(d_human, d_llm)

    # Permutation test
    n = human_pts.shape[0]
    count_ge = 0
    rng = np.random.RandomState(42)
    for _ in range(n_perms):
        perm = rng.permutation(n)
        d_llm_perm = pdist(llm_pts[perm], metric="euclidean")
        r_perm, _ = pearsonr(d_human, d_llm_perm)
        if r_perm >= r_obs:
            count_ge += 1
    p_value = (count_ge + 1) / (n_perms + 1)

    return r_obs, p_value


def _run_procrustes_rsa_for_config(
    X_human, X_llm, human_labels, llm_labels_all, n_pca=5, n_perms=5000,
):
    """Run Procrustes + RSA for all model families on given data matrices.

    Returns dict: {model_type: {disparity, rsa_r, rsa_p, n_langs, ...}}
    """
    from sklearn.decomposition import PCA

    n_max = min(X_human.shape)
    k = min(n_pca, n_max)
    pca = PCA(n_components=n_max, random_state=42)
    human_pca = pca.fit_transform(X_human.values)[:, :k]
    llm_pca = pca.transform(X_llm.values)[:, :k]

    mt_groups = {}
    for i, label in enumerate(llm_labels_all):
        mt = label.rsplit("_", 1)[0]
        lang = label.rsplit("_", 1)[1]
        mt_groups.setdefault(mt, []).append((i, lang))

    human_lang_set = set(human_labels)
    results = {}

    for mt, members in sorted(mt_groups.items()):
        shared_langs, llm_indices, human_indices = [], [], []
        for llm_idx, lang in members:
            if lang in human_lang_set:
                shared_langs.append(lang)
                llm_indices.append(llm_idx)
                human_indices.append(human_labels.index(lang))

        if len(shared_langs) < 5:
            continue

        h_pts = human_pca[human_indices]
        l_pts = llm_pca[llm_indices]

        _, _, disparity = _procrustes_align(h_pts, l_pts)
        rsa_r, rsa_p = _rsa_mantel(h_pts, l_pts, n_perms=n_perms)

        results[mt] = {
            "disparity": disparity,
            "rsa_r": rsa_r,
            "rsa_p": rsa_p,
            "n_langs": len(shared_langs),
            "n_qs": X_human.shape[1],
        }

    return results


def plot_procrustes_rsa(
    llm_dists, human_dists, questions, jsd_df, figures_dir: Path,
):
    """Procrustes + RSA sweep across multiple filter strategies and thresholds.

    Filter types:
    - JSD: exclude questions with mean JSD above threshold
    - Bias: exclude questions with mean position bias above threshold
    - P_valid: exclude questions with mean P_valid below threshold
    - Combined: require P_valid > thresh AND bias < thresh

    Generates:
    - Line plot: RSA r vs number of questions retained, per filter type
    - Line plot: Procrustes disparity vs number of questions retained
    - Best-config Procrustes scatter
    """
    from sklearn.decomposition import PCA

    _, _, all_qs = _prepare_ev_matrices(llm_dists, human_dists, questions)
    all_qs_set = set(all_qs)
    filtered_jsd = jsd_df[~jsd_df["model_type"].isin(MODELS_EXCLUDE)]

    # Compute per-question quality stats (methodology quality, not cultural distance)
    agg_dict = dict(
        mean_jsd=("jsd", "mean"),
        mean_bias=("position_bias_magnitude", "mean"),
    )
    if "p_valid_mean" in filtered_jsd.columns:
        agg_dict["mean_pvalid"] = ("p_valid_mean", "mean")
    q_stats = filtered_jsd.groupby("question_id").agg(**agg_dict).reset_index()
    if "mean_pvalid" not in q_stats.columns:
        q_stats["mean_pvalid"] = 1.0

    print(f"  Per-question quality: P_valid mean={q_stats['mean_pvalid'].mean():.3f}, "
          f"Bias mean={q_stats['mean_bias'].mean():.3f}")

    # Build filter configs: each is (label, filter_type, threshold, excluded_qids, n_kept)
    # Methodology-quality filters (preferred): Bias and P_valid measure whether the
    # LLM produced reliable answers, without penalizing genuine cultural disagreement.
    # JSD filters (for comparison): also remove questions where LLM disagrees with humans,
    # which conflates methodology failures with real cultural signal.
    filter_configs = []

    # P_valid thresholds (exclude low-quality questions)
    for thresh in np.arange(0.75, 0.95, 0.01):
        excl = set(q_stats[q_stats["mean_pvalid"] < thresh]["question_id"])
        n_kept = len(all_qs_set - excl)
        if n_kept >= 10:
            filter_configs.append((f"Pv>{thresh:.2f}", "P_valid", thresh, excl, n_kept))

    # Bias thresholds (exclude high-bias questions)
    for thresh in np.arange(0.20, 0.65, 0.025):
        excl = set(q_stats[q_stats["mean_bias"] > thresh]["question_id"])
        n_kept = len(all_qs_set - excl)
        if n_kept >= 10:
            filter_configs.append((f"Bias<{thresh:.3f}", "Bias", thresh, excl, n_kept))

    # Quality-only combined: P_valid > thresh AND Bias < thresh (no JSD!)
    for pv_t in np.arange(0.78, 0.92, 0.02):
        for bias_t in np.arange(0.30, 0.55, 0.05):
            excl_pv = set(q_stats[q_stats["mean_pvalid"] < pv_t]["question_id"])
            excl_bias = set(q_stats[q_stats["mean_bias"] > bias_t]["question_id"])
            excl = excl_pv | excl_bias
            n_kept = len(all_qs_set - excl)
            if n_kept >= 10:
                filter_configs.append((
                    f"Pv>{pv_t:.2f}+Bias<{bias_t:.2f}", "Quality",
                    (pv_t, bias_t), excl, n_kept,
                ))

    # JSD thresholds (for comparison — note this conflates quality with cultural distance)
    for thresh in np.arange(0.15, 0.55, 0.025):
        excl = set(q_stats[q_stats["mean_jsd"] > thresh]["question_id"])
        n_kept = len(all_qs_set - excl)
        if n_kept >= 10:
            filter_configs.append((f"JSD<{thresh:.3f}", "JSD", thresh, excl, n_kept))

    # No filter baseline
    filter_configs.append(("No filter", "None", None, set(), len(all_qs_set)))

    print(f"  Running {len(filter_configs)} filter configurations...")

    # Run Procrustes+RSA for each config
    sweep_rows = []
    best_rsa = {"r": -1, "config": None, "results": None}

    for label, ftype, thresh, excl, n_kept in filter_configs:
        X_human, X_llm, shared_qs = _prepare_ev_matrices(
            llm_dists, human_dists, questions, exclude_qs=excl if excl else None
        )
        if X_human.shape[1] < 10:
            continue

        results = _run_procrustes_rsa_for_config(
            X_human, X_llm,
            list(X_human.index), list(X_llm.index),
            n_pca=5, n_perms=5000,
        )

        for mt, res in results.items():
            sweep_rows.append({
                "filter_label": label,
                "filter_type": ftype,
                "threshold": str(thresh),
                "n_questions": n_kept,
                "model_type": mt,
                **res,
            })

        # Track best RSA across all models (average)
        if results:
            avg_rsa = np.mean([r["rsa_r"] for r in results.values()])
            if avg_rsa > best_rsa["r"]:
                best_rsa = {"r": avg_rsa, "config": label, "results": results,
                            "excl": excl, "n_kept": n_kept}

    sweep_df = pd.DataFrame(sweep_rows)
    if sweep_df.empty:
        print("  No valid filter configurations produced results")
        return

    # --- Figure 1: RSA r vs n_questions, colored by filter type ---
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))

    type_colors = {
        "Quality": "#2ca02c", "P_valid": "#9467bd", "Bias": "#1f77b4",
        "JSD": "#d62728", "None": "#999999",
    }
    type_markers = {
        "Quality": "D", "P_valid": "^", "Bias": "s",
        "JSD": "o", "None": "*",
    }

    for metric, ax, ylabel, title, better in [
        ("rsa_r", axes[0], "RSA Mantel r", "RSA: Cultural Distance Correlation", "higher"),
        ("disparity", axes[1], "Procrustes Disparity", "Procrustes: Alignment Residual", "lower"),
    ]:
        for mt in sorted(sweep_df["model_type"].unique()):
            mt_df = sweep_df[sweep_df["model_type"] == mt]
            for ftype in sorted(mt_df["filter_type"].unique()):
                sub = mt_df[mt_df["filter_type"] == ftype].sort_values("n_questions")
                color = type_colors.get(ftype, "#999999")
                marker = type_markers.get(ftype, "o")
                mt_label = MODEL_LABELS.get(mt, mt)
                alpha = 0.7
                # Only label once per filter type (first model)
                label = f"{ftype}" if mt == sorted(sweep_df["model_type"].unique())[0] else None
                ax.scatter(sub["n_questions"], sub[metric],
                           c=color, marker=marker, s=20, alpha=alpha)
                if label:
                    ax.plot([], [], color=color, marker=marker, linestyle="none",
                            markersize=6, label=label)

        # Plot per-model trend lines for quality-only filters
        for ftype_line in ["Quality", "P_valid", "Bias"]:
            for mt in sorted(sweep_df["model_type"].unique()):
                sub = sweep_df[(sweep_df["model_type"] == mt) & (sweep_df["filter_type"] == ftype_line)]
                sub = sub.sort_values("n_questions")
                if len(sub) > 1:
                    mt_label = MODEL_LABELS.get(mt, mt)
                    ax.plot(sub["n_questions"], sub[metric],
                            color=MODEL_COLORS.get(mt, "#999999"), linewidth=1,
                            alpha=0.5, linestyle="--" if ftype_line == "JSD" else "-")

        ax.set_xlabel("Number of Questions Retained")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.legend(fontsize=7, loc="best")
        ax.grid(True, alpha=0.3)

    plt.suptitle("Filter Sweep: Procrustes + RSA vs Question Selection (PCA-5)",
                 fontsize=13, fontweight="bold")
    plt.tight_layout(rect=[0, 0, 1, 0.94])
    out = figures_dir / "F5_filter_sweep.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  Saved {out}")

    # Print best config
    print(f"\n  Best config (avg RSA r={best_rsa['r']:.3f}): {best_rsa['config']} "
          f"({best_rsa['n_kept']} questions)")
    for mt, res in sorted(best_rsa["results"].items()):
        sig = "***" if res["rsa_p"] < 0.001 else "**" if res["rsa_p"] < 0.01 else \
              "*" if res["rsa_p"] < 0.05 else "n.s."
        print(f"    {MODEL_LABELS.get(mt, mt)}: d={res['disparity']:.3f}, "
              f"RSA r={res['rsa_r']:.3f} ({sig}, p={res['rsa_p']:.4f})")

    # --- Figure 2: Best-config Procrustes scatter ---
    excl = best_rsa["excl"]
    X_human, X_llm, shared_qs = _prepare_ev_matrices(
        llm_dists, human_dists, questions, exclude_qs=excl if excl else None
    )
    human_labels = list(X_human.index)
    llm_labels_all = list(X_llm.index)

    n_max = min(X_human.shape)
    k = min(5, n_max)
    pca = PCA(n_components=n_max, random_state=42)
    human_pca = pca.fit_transform(X_human.values)[:, :k]
    llm_pca = pca.transform(X_llm.values)[:, :k]

    mt_groups = {}
    for i, label in enumerate(llm_labels_all):
        mt = label.rsplit("_", 1)[0]
        lang = label.rsplit("_", 1)[1]
        mt_groups.setdefault(mt, []).append((i, lang))

    human_lang_set = set(human_labels)
    n_models = len([mt for mt in mt_groups if mt not in MODELS_EXCLUDE])
    fig, axes = plt.subplots(1, n_models, figsize=(7 * n_models, 7), squeeze=False)
    axes = axes[0]
    plot_idx = 0

    for mt, members in sorted(mt_groups.items()):
        if mt in MODELS_EXCLUDE:
            continue
        shared_langs, llm_indices, human_indices = [], [], []
        for llm_idx, lang in members:
            if lang in human_lang_set:
                shared_langs.append(lang)
                llm_indices.append(llm_idx)
                human_indices.append(human_labels.index(lang))

        if len(shared_langs) < 5:
            continue

        h_pts = human_pca[human_indices]
        l_pts = llm_pca[llm_indices]
        h_proc, l_proc, disparity = _procrustes_align(h_pts, l_pts)
        rsa_r, rsa_p = _rsa_mantel(h_pts, l_pts, n_perms=5000)

        ax = axes[plot_idx]
        plot_idx += 1

        for i, lang in enumerate(shared_langs):
            ax.plot([h_proc[i, 0], l_proc[i, 0]],
                    [h_proc[i, 1], l_proc[i, 1]],
                    color="#cccccc", linewidth=0.8, alpha=0.5, zorder=1)

        for i, lang in enumerate(shared_langs):
            cluster = LANG_TO_CLUSTER.get(lang, "Other")
            color = CLUSTER_COLORS.get(cluster, "#999999")
            ax.scatter(h_proc[i, 0], h_proc[i, 1], c=color, s=200,
                       edgecolors="black", linewidths=1.2, zorder=5, marker="o")
            ax.annotate(LANG_NAMES.get(lang, lang),
                        (h_proc[i, 0], h_proc[i, 1]),
                        textcoords="offset points", xytext=(7, 7),
                        fontsize=7, fontweight="bold", alpha=0.9)

        marker = MODEL_MARKERS.get(mt, "D")
        for i, lang in enumerate(shared_langs):
            cluster = LANG_TO_CLUSTER.get(lang, "Other")
            color = CLUSTER_COLORS.get(cluster, "#999999")
            ax.scatter(l_proc[i, 0], l_proc[i, 1], c=color, s=80,
                       marker=marker, edgecolors="black", linewidths=0.5,
                       alpha=0.7, zorder=3)
            ax.annotate(LANG_NAMES.get(lang, lang),
                        (l_proc[i, 0], l_proc[i, 1]),
                        textcoords="offset points", xytext=(4, 4),
                        fontsize=5, alpha=0.5)

        sig = "***" if rsa_p < 0.001 else "**" if rsa_p < 0.01 else \
              "*" if rsa_p < 0.05 else "n.s."
        mt_label = MODEL_LABELS.get(mt, mt)
        ax.set_title(f"{mt_label}\nd={disparity:.3f}, RSA r={rsa_r:.3f}{sig}",
                     fontsize=11, fontweight="bold")
        ax.set_xlabel("Procrustes dim 1")
        ax.set_ylabel("Procrustes dim 2")
        ax.grid(True, alpha=0.2)
        ax.set_aspect("equal")

    plt.suptitle(
        f"Procrustes (best config: {best_rsa['config']}, {best_rsa['n_kept']} qs, PCA-5)",
        fontsize=14, fontweight="bold",
    )
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    out = figures_dir / "F5_procrustes.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  Saved {out}")


# ── Legacy figures (kept for supplementary) ──────────────────────────────────

def plot_jsd_by_qtype(jsd_df: pd.DataFrame, figures_dir: Path):
    """Box/violin plots of JSD to human by response type and model type."""
    filtered = jsd_df[~jsd_df["model_type"].isin(MODELS_EXCLUDE)]
    fig, ax = plt.subplots(figsize=(10, 6))

    order = sorted(filtered["response_type"].unique())
    sns.boxplot(
        data=filtered, x="response_type", y="jsd", hue="model_type",
        order=order, ax=ax, fliersize=2, linewidth=0.8,
    )
    ax.set_xlabel("Response Type")
    ax.set_ylabel("JSD (LLM vs Human)")
    ax.set_title("JSD to Human Data by Question Type")
    ax.legend(title="Model Type")
    ax.grid(True, alpha=0.3, axis="y")
    ax.tick_params(axis="x", rotation=30)

    plt.tight_layout()
    out = figures_dir / "human_jsd_by_qtype.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  Saved {out}")


def plot_model_comparison(jsd_df: pd.DataFrame, figures_dir: Path):
    """Grouped bar chart comparing all model types' mean JSD to human per language."""
    filtered = jsd_df[~jsd_df["model_type"].isin(MODELS_EXCLUDE)]
    lang_jsd = filtered.groupby(["model_type", "lang"]).agg(
        mean_jsd=("jsd", "mean"),
    ).reset_index()

    model_types = sorted(lang_jsd["model_type"].unique())
    per_model_langs = [set(lang_jsd[lang_jsd["model_type"] == mt]["lang"]) for mt in model_types]
    shared_langs = sorted(set.intersection(*per_model_langs)) if per_model_langs else []

    if not shared_langs:
        print("  No shared languages for model comparison")
        return

    model_series = {}
    for mt in model_types:
        sub = lang_jsd[lang_jsd["model_type"] == mt].set_index("lang")["mean_jsd"]
        model_series[mt] = sub

    n_models = len(model_types)
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))

    ax = axes[0]
    x = np.arange(len(shared_langs))
    width = 0.8 / n_models
    for i, mt in enumerate(model_types):
        offset = (i - (n_models - 1) / 2) * width
        vals = [model_series[mt][l] for l in shared_langs]
        ax.bar(x + offset, vals, width * 0.9,
               label=MODEL_LABELS.get(mt, mt),
               color=MODEL_COLORS.get(mt, "#999999"),
               edgecolor="black", linewidth=0.5)
    ax.set_xticks(x)
    ax.set_xticklabels([LANG_NAMES.get(l, l) for l in shared_langs],
                       rotation=45, ha="right", fontsize=8)
    ax.set_ylabel("Mean JSD to Human Data")
    ax.set_title("(a) Mean JSD to Human by Language")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3, axis="y")

    # Win count bar chart
    ax = axes[1]
    win_counts = {mt: 0 for mt in model_types}
    for lang in shared_langs:
        best = min(model_types, key=lambda mt: model_series[mt][lang])
        win_counts[best] += 1
    labels_bar = [MODEL_LABELS.get(mt, mt) for mt in model_types]
    counts = [win_counts[mt] for mt in model_types]
    colors = [MODEL_COLORS.get(mt, "#999999") for mt in model_types]
    ax.bar(labels_bar, counts, color=colors, edgecolor="black", linewidth=0.5)
    ax.set_ylabel("Number of Languages (closest to human)")
    ax.set_title(f"(b) Model Wins across {len(shared_langs)} Languages")
    ax.grid(True, alpha=0.3, axis="y")
    for i, (lbl, cnt) in enumerate(zip(labels_bar, counts)):
        ax.text(i, cnt + 0.3, str(cnt), ha="center", fontsize=10, fontweight="bold")

    plt.tight_layout()
    out = figures_dir / "human_model_comparison.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  Saved {out}")


# ── CLI ──────────────────────────────────────────────────────────────────────

def run_figure(
    figure: str,
    jsd_df: pd.DataFrame,
    llm_dists: dict,
    human_dists: dict,
    questions: dict,
    figures_dir: Path,
):
    """Dispatch to individual figure generators.

    Figures used in the analysis report (--figure report):
        F2_inglehart_welzel.png   — Inglehart-Welzel cultural map
        F3_ev_scatter.png         — EV scatter with z-scored row
        F4_jsd_heatmap.png        — Bias-weighted JSD heatmap
        F4_jsd_distribution.png   — Per-question JSD histogram
        F5_deepdive.png           — Per-question deep dive (3×3 grid)
        F5_umap_grid.png          — 4×2 UMAP grid (metric × filter + uncentered)
        jsd_vs_bias.png           — JSD vs position bias diagnostic
        umap_sensitivity.png      — UMAP hyperparameter sensitivity sweep
      (F6_pvalid_heatmap.png and F7_position_bias.png are generated by analyze.py)
    """
    # Report figures: exactly what the typst report references
    report_figs = ("report", "all")

    if figure in (*report_figs, "umap_grid"):
        print("\n  Generating UMAP Grid (4×2: metric × filter)...")
        try:
            plot_umap_grid(llm_dists, human_dists, questions, jsd_df, figures_dir)
        except ImportError:
            print("  Skipping UMAP grid: umap-learn not installed")

    if figure in (*report_figs, "jsd_dist"):
        print("\n  Generating JSD Distribution...")
        plot_jsd_distribution(jsd_df, figures_dir)

    if figure in (*report_figs, "iw"):
        print("\n  Generating Inglehart-Welzel Composite...")
        iw_df = compute_iw_composites(llm_dists, human_dists, questions)
        if not iw_df.empty:
            plot_iw_composite(iw_df, figures_dir)
        else:
            print("  Skipping IW: insufficient question data")

    if figure in (*report_figs, "scatter"):
        print("\n  Generating EV Scatter + Z-Score...")
        plot_scatter_ev(jsd_df, figures_dir)

    if figure in (*report_figs, "heatmap"):
        print("\n  Generating JSD Heatmap...")
        plot_jsd_heatmap(jsd_df, figures_dir)

    if figure in (*report_figs, "deepdive"):
        print("\n  Generating Deep Dive...")
        plot_deepdive(jsd_df, llm_dists, human_dists, figures_dir)

    if figure in (*report_figs, "jsd_vs_bias"):
        print("\n  Generating JSD vs Bias scatter...")
        plot_jsd_vs_bias(jsd_df, figures_dir)

    if figure in (*report_figs, "umap_sensitivity"):
        print("\n  Generating UMAP Sensitivity sweep...")
        try:
            plot_umap_sensitivity(llm_dists, human_dists, questions, jsd_df, figures_dir)
        except ImportError:
            print("  Skipping UMAP sensitivity: umap-learn not installed")

    if figure in (*report_figs, "pca"):
        print("\n  Generating PCA cultural geography...")
        plot_pca_comparison(llm_dists, human_dists, questions, jsd_df, figures_dir)

    # Supplementary figures only when running "all" or explicitly
    if figure in ("all", "procrustes"):
        print("\n  Generating Procrustes + RSA alignment...")
        plot_procrustes_rsa(llm_dists, human_dists, questions, jsd_df, figures_dir)

    if figure == "all":
        print("\n  Generating supplementary figures...")
        plot_jsd_by_qtype(jsd_df, figures_dir)
        plot_model_comparison(jsd_df, figures_dir)


def main():
    PROJECT_ROOT = Path(__file__).resolve().parent.parent

    parser = argparse.ArgumentParser(
        description="Compare LLM cultural value distributions to human survey data"
    )
    parser.add_argument("--results-dir", type=Path,
                        default=PROJECT_ROOT / "results")
    parser.add_argument("--human", type=Path,
                        default=PROJECT_ROOT / "human_data" / "data" / "human_distributions.parquet")
    parser.add_argument("--questions", type=Path,
                        default=PROJECT_ROOT / "data" / "questions.json")
    parser.add_argument("--figures-dir", type=Path,
                        default=PROJECT_ROOT / "figures")
    parser.add_argument("--db", type=str, default=None,
                        help="Path to survey.db (loads LLM + human data from DB)")
    parser.add_argument("--figure", type=str, default="all",
                        choices=["all", "report", "umap_grid", "umap_sensitivity", "pca", "procrustes", "iw", "scatter", "heatmap", "jsd_dist", "deepdive", "jsd_vs_bias"],
                        help="Which figure to generate (default: all). "
                             "'report' generates only the 6 figures used in analysis_report.typ "
                             "and compiles the PDF.")
    args = parser.parse_args()

    args.figures_dir.mkdir(parents=True, exist_ok=True)

    # Load data
    print("Loading data...")
    llm_df = load_llm_results(args.results_dir, db_path=args.db)
    if args.db:
        from db.load import load_human_distributions
        human_df = load_human_distributions(args.db)
    else:
        human_df = pd.read_parquet(args.human)
    questions = load_question_metadata(args.questions)
    print(f"Human data: {len(human_df)} rows, "
          f"{human_df['lang'].nunique()} languages, "
          f"{human_df['question_id'].nunique()} questions")

    # Build distribution lookups
    print("\nBuilding distributions...")
    llm_dists = build_distributions(
        llm_df, "prob_averaged", ["model_type", "lang", "question_id"]
    )
    human_dists = build_distributions(
        human_df, "prob_human", ["lang", "question_id"]
    )
    print(f"  LLM distributions: {len(llm_dists)}")
    print(f"  Human distributions: {len(human_dists)}")

    # Compute JSD for all (model_type, lang, question_id) triples
    print("\nComputing JSD...")
    jsd_df = compute_jsd_per_question(llm_dists, human_dists, questions)
    print(f"  Computed {len(jsd_df)} JSD values")

    if jsd_df.empty:
        print("ERROR: No overlapping (model_type, lang, question_id) between LLM and human data")
        sys.exit(1)

    # Join position bias and P_valid data for quality-weighted metrics
    if "position_bias_magnitude" in llm_df.columns:
        llm_df["_p_valid_avg"] = (llm_df["p_valid_forward"] + llm_df["p_valid_reversed"]) / 2
        quality_df = llm_df.groupby(
            ["model_type", "lang", "question_id"]
        ).agg(
            position_bias_magnitude=("position_bias_magnitude", "first"),
            p_valid_mean=("_p_valid_avg", "mean"),
        ).reset_index()
        jsd_df = jsd_df.merge(
            quality_df, on=["model_type", "lang", "question_id"], how="left"
        )
        jsd_df["bias_weight"] = 1.0 - jsd_df["position_bias_magnitude"].fillna(0).clip(0, 1)
        jsd_df["p_valid_mean"] = jsd_df["p_valid_mean"].fillna(0.0)
        print(f"  Added bias weights (mean weight: {jsd_df['bias_weight'].mean():.3f})")
        print(f"  Added P_valid (mean: {jsd_df['p_valid_mean'].mean():.3f})")
    else:
        jsd_df["position_bias_magnitude"] = 0.0
        jsd_df["bias_weight"] = 1.0
        jsd_df["p_valid_mean"] = 1.0

    # Print summary
    print_summary(jsd_df)

    # Generate figures
    fig_dir = args.figures_dir
    if args.figure == "report":
        fig_dir = args.figures_dir / "main"
        fig_dir.mkdir(parents=True, exist_ok=True)
    print(f"\nGenerating figures in {fig_dir}/...")
    run_figure(args.figure, jsd_df, llm_dists, human_dists, questions, fig_dir)

    # Save JSD data for further analysis
    out = args.figures_dir.parent / "human_comparison.parquet"
    jsd_df.to_parquet(out, index=False)
    print(f"\nSaved comparison data to {out}")

    # Compile typst report when generating report figures
    if args.figure == "report":
        import shutil
        import subprocess
        report_typ = args.figures_dir / "analysis_report.typ"
        if report_typ.exists() and shutil.which("typst"):
            print(f"\nCompiling {report_typ}...")
            result = subprocess.run(
                ["typst", "compile", str(report_typ)],
                capture_output=True, text=True,
            )
            if result.returncode == 0:
                print(f"  Saved {report_typ.with_suffix('.pdf')}")
            else:
                print(f"  typst compile failed: {result.stderr.strip()}")
        elif not report_typ.exists():
            print(f"\n  Skipping typst compile: {report_typ} not found")
        else:
            print("\n  Skipping typst compile: typst not installed")

    print("\nDone!")


if __name__ == "__main__":
    main()
